"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PORT = exports.babelDatabase = void 0;
const classes_1 = require("./classes");
const SUDOuser = new classes_1.User('SUDOuser');
SUDOuser.setEmail = 'dudiest@dude.org';
SUDOuser.setPassword = 'SUDOpassword';
SUDOuser.setUrls = { "s8h76q": "https://www.google.com", "asd832": "https://www.youtube.com" };
const PORT = 4040;
const babelDatabase = new classes_1.Database();
var constants_1 = require("./constants");
Object.defineProperty(exports, "babelDatabase", { enumerable: true, get: function () { return constants_1.babelDatabase; } });
Object.defineProperty(exports, "PORT", { enumerable: true, get: function () { return constants_1.PORT; } });
